/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic;

public class OperacoesComString {
    
    public static void main(String[] args) {
       
        var nome = "Andre";
        var sobreNome = "Gomes";
        final var nomeCompleto = nome + sobreNome;
        
        System.out.println(nome);        
        System.out.println("Nome: " + nome);
        System.out.println("Nome completo: " + nomeCompleto);
        var string = new String(" Minha String ");
        
        System.out.println("Char na posicao: "+ string.charAt(5));
        System.out.println("Quantidade = "+ string.length());
        System.out.println("Sem Trim [" + string + "]");
        System.out.println("Com Trim [" + string.trim() + "]");
        System.out.println("Lower "+ string.toLowerCase());
        System.out.println("Upper " + string.toUpperCase());
        System.out.println("Contem M? " + string.contains("M"));
        System.out.println("Contem X? " + string.contains("X"));
        System.out.println("Replace "+ string.replace("n","S"));
        System.out.println("Equals? " + string.equals("Minha String"));
        System.out.println("EqualsIgnoreCase? " + 
                string.equalsIgnoreCase("minha sTring"));
        System.out.println("Substring(1,6)=" + string.substring(1,6));
        
        var nome2 = "Dave";
        final var builder = new StringBuilder(nome2);
        
        System.out.println("\n" + builder.append("Eddie"));
        
        final var reverse = builder.reverse();
        System.out.println(reverse);
        
        final var insert = reverse.insert(0, "#").insert(reverse.length(), "#");
        System.out.println(insert);
        
        System.out.println("\nA B C D E F G".toCharArray());
        System.out.println("Aula de Java".split(""));
        System.out.println("Aula".concat(" de Java "));
        System.out.println("1234 asda qw".replaceAll("[0-9]","#"));
    }
}
